name: Master Branch Push Test

on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    outputs:
      release_tag: ${{ steps.get-release-tag.outputs.release_tag }}

    steps:
      - uses: actions/checkout@v3

      - name: Set Releas Tag
        id: get-release-tag
        run: |
          RELEASE_TAG=$(bash ./get_release_tag.sh HEAD)
          echo "RELEASE_TAG is ${RELEASE_TAG}"
          echo "::set-output name=release_tag::${RELEASE_TAG}"
