name: Test

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  actions: read
  contents: read

env:
  TZ: 'Asia/Tokyo'

jobs:
  first:
    name: First
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: one
        run: echo foo

  second:
    name: Second
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: second
        run: exit 1

  third:
    name: Third
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: technote-space/workflow-conclusion-action@v1

      - name: Run
        run: echo ${{ env.WORKFLOW_CONCLUSION }}

      - name: Return Failure
        if: ${{ !contains(env.WORKFLOW_CONCLUSION, 'success') }}
        run: exit 1
