name: Test

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  actions: read
  contents: read

env:
  TZ: 'Asia/Tokyo'

jobs:
  first:
    name: First
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: one
        run: |
            mkdir hoge

  second:
    name: Second
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: second
        run: |
            mkdir fuga
            mkdir fuga

  third:
    name: Third
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: third
        run: echo ${{ job.status }}
